spring:
  application:
    name: projeto-base
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/projetobase?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 
  profiles:
    active: develop
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-bean-definition-overriding: true

client:
  secret:
    webapp: fZ2Fpb0Bob3RtYWlsLm
  jwt:
    signature: CerberusItTokenSignature
    accessToken:
      expiration: 86400
    refreshToken:
      expiration: 604800